### ISSUE TITLE
Configuration Problem with oracle database

### ISSUE THREAD

**Issue by thr8088** [traccar/traccar#4130]
```
<entry key='database.driverFile'>C:\Program Files\Traccar\lib\ojdbc7.jar</entry>
<entry key='database.driver'>oracle.jdbc.OracleDriver</entry>
<entry key='database.url'>jdbc:oracle:thin:trcaa/trcaa@localhost:1521:trcaa</entry>
<entry key='database.user'>trcaa</entry>
<entry key='database.password'>trcaa</entry>

```

```
ssLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 10:24:58 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 10:32:26 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 10:44:28 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 10:54:42 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 11:07:14 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 11:22:57 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 11:40:39 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 13:00:29 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
```

**We tried to configure traccar with oracle database using all this jar files**  

- [x] ojdbc5
- [x] ojdbc6
- [x] ojdbc7
- [x] ojdbc14 

**but there same problem in log file**

database version: oracle 11g r2 enterprise edition
database working without any problems and the connection is correct

log file and configuration file attached

we need support to solve this issue by sending configuration file with oracle database

thanks a lot

**Comment by tananaev** [comment]
Enable full stack traces using following boolean config parameter:
```
logger.fullStackTraces
```

**Comment by thr8088** [comment]
I enabled full stack traces by adjusting the following commands:

```
    <entry key='logger.enable'>true</entry>
    <entry key='logger.fullStackTraces'>true</entry>
    <entry key='logger.level'>info</entry>
    <entry key='logger.file'>./logs/tracker-server.log</entry>
```
and got the following results:

```
2018-10-31 09:37:34  WARN: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=14h1m23s819ms129�s200ns).
2018-10-31 10:15:42 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 10:24:58 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 10:32:26 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 10:44:28 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 10:54:42 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 11:07:14 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 11:22:57 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 11:40:39 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 13:00:29 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 13:53:15 ERROR: Main method error - oracle.jdbc.OracleDriver - ClassNotFoundException (... < DataManager:114 < *:90 < Context:382 < Main:110 < ...)
2018-10-31 14:02:12 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-11-01 09:38:53 ERROR: Main method error - java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader - ClassCastException (DataManager:106 < *:90 < Context:382 < Main:110 < ...)
2018-11-01 09:50:03 ERROR: Main method error - 
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.traccar.database.DataManager.initDatabase(DataManager.java:106)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:382)
	at org.traccar.Main.run(Main.java:110)
	at org.traccar.Main$1.run(Main.java:88)
	at org.traccar.WindowsService$ServiceMain.callback(WindowsService.java:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
```

**Comment by tananaev** [comment]
I have fixed the issue.

**Comment by thr8088** [comment]
The problem still exists
There is no connection to the database

**Comment by thr8088** [comment]
This is the error log

```
2018-11-03 05:35:09  WARN: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1d6h43m6s491ms944�s400ns).
2018-11-03 07:19:30 ERROR: Main method error - 
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.traccar.database.DataManager.initDatabase(DataManager.java:106)
	at org.traccar.database.DataManager.<init>(DataManager.java:90)
	at org.traccar.Context.init(Context.java:382)
	at org.traccar.Main.run(Main.java:110)
	at org.traccar.Main$1.run(Main.java:88)
	at org.traccar.WindowsService$ServiceMain.callback(WindowsService.java:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
```

When you log on http: // localhost: 8082

do not work

**Comment by tananaev** [comment]
You haven't answered my first question.

**Comment by thr8088** [comment]
The version was traccar-windows-4.0
Then you install Trac Windows-64-4.1

**Comment by tananaev** [comment]
I just fixed it yesterday, so the fix is obviously not included in version 4.1.

**Comment by thr8088** [comment]
These are not the same settings for binding only when you change the connection settings for mysql

`2018-10-31 09:37:34  WARN: HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=14h1m23s819ms129�s200ns).
`

My problem is only with oracle link

**Comment by FREB91** [comment]
Hi!.
i think i have the same problem but i use linux.
my Traccar version is  traccar-linux-64-4.5.
oracle 11g XE.

this is my conf file.
    <entry key='database.driverFile'>/opt/traccar/lib/ojdbc7.jar</entry> (I AM SURE THAT THE FILE IS HERE)
    <entry key='database.driver'>oracle.jdbc.OracleDriver</entry>
    <entry key='database.url'>jdbc:oracle:thin:gps/gps@localhost:1521:xe</entry>
    <entry key='database.user'>gps</entry>
    <entry key='database.password'>gps</entry>
    <entry key='database.checkConnection'>SELECT 1 FROM DUAL</entry>

here is the log file (also attached)

2019-06-14 14:27:28 ERROR: Main method error - Unable to make void jdk.internal.loader.ClassLoaders$AppClassLoader.appendToClassPathForInstrumentation(java.lang.String) accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @38425407 - InaccessibleObjectException (... < DataManager:113 < *:89 < Context:292 < Main:110 < ...)

I have successfully configure with mysql and postgres but with oracle i just cant do it.

Can someone help me please?

[tracker-server.log](https://github.com/traccar/traccar/files/3291053/tracker-server.log)

**Comment by tananaev** [comment]
@FREB91 try using older version of Java.

**Comment by anjumsohail** [comment]
Same issue with me as well. Which version of java should be used
