### ISSUE TITLE
HTML entities ( # <'> & ")  in edit dialogs and map name not decoded.

### ISSUE THREAD

**Issue by skizzofly** [traccar/traccar#4283]
Hello, thanks for the hard work you are doing.
I noticed that from Traccar 4.1 the HTML entities are present in the display on map.

this happens with names that have  a quote, like for example 
Gianni D'amato, and it also happnes when there is a < or a > or a &.. 
I get Gianni D & #39;amato in map display and in edit device ,
the same happens for all names, gefences, calculated attributes..
In list view it's OK but in edit the html entity come out..
For the map view a need to modifiy js adding some Ext.String.htmlDecode(device.get('name')).. 
I guess this was introduced after the security fixes in 4.1, to prevent haking
It's not a DB issue, special chars like òàùìèé work all fine, only < > & # ' " and some other chars give te problem..
in my case the real problem is with the single quote as we have some surnames with ' inside.
My installation runs on mysql, but i tried a vanllia installation on H2...
On 4.0 all ok, on 4.1 issue is present.  

We are using Traccar for hangglider and paraglider tracking.

**Comment by tananaev** [comment]
Have you tried 4.3? We don't really accept bugs in older versions.

**Comment by skizzofly** [comment]
Anton, yes, of course ;-) 
I upgraded from 4.0 to 4.3 on fresh installation yesterday, and it's on the 4.3 that i first found the problem, then on a an other machine  versions after the 4.0 so i installed 4.1 to see if the issue was present.. (this to check from what version the problem started) and it started form there.. i think it'a related with the sanitasion of the strings, maybe intruced with this commit
https://github.com/traccar/traccar/commit/fac0cc89583d9294285af84853b2f9e7a02fb46c

I first taught it was a charset issue of the mysql i use, so i tried with the native H2 DB , and the problem persisted.
To reproduce i'ts simple, just add a device with one of that chars in the name, and in edit you will get it.
In the reply json also it will be present
The browser used is chrome  73.0.3683.103 did not try with other browsers..

**Comment by tananaev** [comment]
Fixed in https://github.com/traccar/traccar-web/commit/04a92f0fbae8cee0e88b56e736a6c4178d39ca35.

**Comment by skizzofly** [comment]
Now on all menu's and edit it works fine,
but on map display the issue is still present, the issue is also present on
geo aera's name on the map.

**Comment by tananaev** [comment]
Create a separate ticket for it. Make sure it's in the right repo - `traccar-web`.
