### ISSUE TITLE
4.13 Issue with Mictrack MT700 

### ISSUE THREAD

**Issue by netsound** [traccar/traccar#4687]
Just upgraded from 4.12 to 4.13 and the MT700 devices that are sending tlt2h to 5030 are throwing the following errors:
```
error - NullPointerException (FilterHandler:84 < *:161 < *:200 < BaseDataHandler:27 < ... < *:29 < ... < ExtendedObjectDecoder:61 < ...)
```
for every packet that comes in...  The web server shows the devices going online/offline with every packet.

Doing a hexdeocde.. It's missing some data.. if i downgrade to 4.12 I get proper data in the log.

Here is a decode from 4.13 of the device:
```
#860517049474313#MT700#0000#AUTO#1
#35$GPRMC,,V,,,,,,,,,,A*5C
##
```

Here is a decode when I downgrade to 4.12   Same device.. Never even turned it off between version changes.
```
#860517049474313#MT700#0000#DEF#1
#35$GPRMC,041833.00,A,4247.8458,N,08342.6970,W,,314.80,020621,,,A*57
##
```

**Comment by tananaev** [comment]
Please enable `logger.fullStackTraces` in the config and provide a log fragment from "connected" to the error without filtering or decoding anything.

**Comment by netsound** [comment]
Here ya go:


2021-06-02 00:53:47  INFO: [3bbb8ba3] connected
2021-06-02 00:53:47  INFO: [3bbb8ba3: tlt2h < 12.153.231.178] HEX: 23383630353137303439343731333632234d543730302330303030234155544f23310d0a233336244750524d432c2c562c2c2c2c2c2c2c2c2c2c412a35430d0a23230d0a
2021-06-02 00:53:47  WARN: [3bbb8ba3] error -
java.lang.NullPointerException
	at org.traccar.handler.FilterHandler.filterFuture(FilterHandler.java:84)
	at org.traccar.handler.FilterHandler.filter(FilterHandler.java:161)
	at org.traccar.handler.FilterHandler.handlePosition(FilterHandler.java:200)
	at org.traccar.BaseDataHandler.channelRead(BaseDataHandler.java:27)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.traccar.BaseDataHandler.channelRead(BaseDataHandler.java:29)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.traccar.ExtendedObjectDecoder.channelRead(ExtendedObjectDecoder.java:61)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.traccar.WrapperContext.fireChannelRead(WrapperContext.java:102)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at org.traccar.WrapperInboundHandler.channelRead(WrapperInboundHandler.java:57)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.traccar.WrapperContext.fireChannelRead(WrapperContext.java:102)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at org.traccar.WrapperInboundHandler.channelRead(WrapperInboundHandler.java:57)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at org.traccar.handler.StandardLoggingHandler.channelRead(StandardLoggingHandler.java:43)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.traccar.handler.NetworkMessageHandler.channelRead(NetworkMessageHandler.java:37)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

2021-06-02 00:53:47  INFO: [3bbb8ba3] disconnected

**Comment by tananaev** [comment]
The issue is fixed.

**Comment by adahmen** [comment]
Is the fix part of the latest docker image?
If yes - I have the latest image installed and I still have the issue (because I have the latest image installed).
If not - How can I install the fix?

**Comment by tananaev** [comment]
It's going to be included in the next release. If you want the fix now, you can make a build from the source code yourself.

**Comment by adahmen** [comment]
Hhhmmmm - never did this before and I need a docker container :-(

Can I revert back to 4.12?
There was a database change (rename of one column). 
Is it enough to rename the column back to the name before?
