### ISSUE TITLE
Traccar 5.1: geofenceIds should be an array of integers, but can return null/None

### ISSUE THREAD

**Issue by oopiicaa** [traccar/traccar#4890]
**Describe the bug**
Home Assistant is reporting "Error setting up platform legacy traccar" since upgrading to Traccar 5.1. If Traccar is downgraded to 5.0, the error is gone - the platform is working normally.

**To Reproduce**
Install Traccar 5.1. Home Assistant with already configured platform is reporting an error after booting.

**Expected behavior**
The platform should work.

**Desktop (please complete the following information):**
 - OS: Traccar on Windows 10 x64

**Additional context**
See [this thread](https://github.com/home-assistant/core/issues/74134#issuecomment-1181696889)

**Comment by oopiicaa** [comment]
Thank you.

**Comment by oopiicaa** [comment]
@tananaev when entering settings for my vehicles or entering settings for Geofences, I get an error (red pop-up) on preview version now:
`class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap') (through reference chain: org.traccar.model.Device["geofenceIds"]->java.util.ArrayList[0])`

**Comment by tananaev** [comment]
Fixed.

**Comment by oopiicaa** [comment]
Hi @tananaev - first issue is still present in 5.2. I suppose it should be fixed?

**Comment by tananaev** [comment]
Should be fixed.

**Comment by oopiicaa** [comment]
I still have the exact same issue on Home Assistant with Traccar 5.2 (also upgraded package pytraccar to 0.10.1). With Traccar downgraded to 5.0, it works fine.

**Comment by tananaev** [comment]
The issue is with the `pytraccar`. Maybe need to wait for a new version?

**Comment by rmcginty** [comment]
I don't think is because of pytraccar.  I am using Postman to directly access my 5.2 server and the result of the GET /devices call has devices with "geofenceIds": null.  Postman reports that these values do not validate against the OpenAPI schema stating that the body of that property must be an array.  It is also reporting that contact and model must be string instead of nulls on devices where I did not enter a value.  That can easily be worked around by entering a value, but there is no workaround if the geofenceId is set to null.

**Comment by tananaev** [comment]
Most of the values are nullable. If you found an issue in the documentation, feel free to send a pull request.
