### ISSUE TITLE
RedisBroadcastService getting stuck with errors, in case of connection interruption to Redis cluster

### ISSUE THREAD

**Issue by tamcore** [traccar/traccar#5233]
**Describe the bug**
If the connection between Traccar and the Redis cluster dies for any reason, the connection is not automatically reestablished and logs are spammed with logs like

```
2023-12-11 14:39:40  WARN: Broadcast failed -
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe (Write failed)
at redis.clients.jedis.Connection.flush(Connection.java:341)
at redis.clients.jedis.Connection.getIntegerReply(Connection.java:292)
at redis.clients.jedis.Jedis.publish(Jedis.java:7937)
at org.traccar.broadcast.RedisBroadcastService.sendMessage(RedisBroadcastService.java:71)
```

**To Reproduce**
1. Configure traccar with `broadcast.type redis`
2. Point `broadcast.address` against a redis instance with a configured timeout (or just manually interrupt the connection, once everything is up and running)
3. Monitor Redis client list with `redis-cli -h 1.2.3.4 client list | grep jedis` until all clients are gone
4. Send data to traccar instance
5. => Receive errors in logs

**Expected behavior**
Have traccar reestablish the lost connection to Redis and resend the failed broadcast message. 

**Additional context**
Running version v5.10 in Kubernetes with multiple traccar replicas pointing against a redis-cluster behind haproxy.

**Comment by radokristof** [comment]
I have the same issue. Were there any updates to redis since this issue?

**Comment by tananaev** [comment]
No updates for now.

**Comment by radokristof** [comment]
I'm happy to contribute. Will see if this can be easily fixed/implemented with your suggestion to use JedisPool instead of the current single connections

**Comment by tananaev** [comment]
Sounds good, thanks.

**Comment by radokristof** [comment]
Maybe it would be better to use Redisson instead of Jedis so Sentinel and other redis deployment mode support can be added easily
https://redisson.pro/docs/configuration/#sentinel-mode

**Comment by tananaev** [comment]
What's the problem with Jedis? It should also support sentinel mode.

**Comment by tananaev** [comment]
Migrated to Jedis pool. It should solve the original problem.

**Comment by radokristof** [comment]
@tananaev I think I still see issues related to this.
I had two instance configured in Kubernetes. Redis and Traccar was restarted one Traccar instance started before Redis restart. 

After restart it seemed that only a subset of device positions reported through the websocket, I think mainly because one of the instance failed to connect to redis

**Comment by tananaev** [comment]
You think? Do you have some evidence?

**Comment by radokristof** [comment]
Unfortunately no, because I had to solve this fast, but I will try to reproduce it and gather evidence.
After restarting traccar, everything went back to normal
